### ISSUE TITLE
Admin Plans / Moderation (projects list & new save widget)

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2182]
To do after #2181 

- To define: 
  - Confirm how to indicate default setting for items? On a per Plan basis, in Plan Conf: setting Moderation flow: Yes | No
  - Permissions - Permissions that should be available to assign to a group
    - Plan Admin: can create and admin plan (Conf tab)
    - Plan Moderator: can moderate projects
    - Plan Editor: can send and edit their plans

- In project list: 
  - [ ] Filter:
    - All
    - Not sent
    - Sent
    - In revision
    - Approved
    - Discarded
- In Project - Save Widget
  - [ ] Show moderation status
  - [ ] Allow to send for moderation
  - [ ] Control Publication action based on Moderation status

- For Plan Moderator: 
  - [ ] Widget moderation ([markup in project page](http://madrid.gobierto.test:3000/sandbox/admin_plans_plan_projects_project)) 
![image](https://user-images.githubusercontent.com/24740/54918704-41dadc00-4eff-11e9-95de-8c63ae168c2e.png)

**Comment by entantoencuanto** [comment]
Pending tasks:
- [x] Role management in admin groups. Allow selection of manage, edit and moderate in modules
- [x] Add author to projects. A project can be created by an admin with edit permission
- Permissions of admins (#2209):
  - [ ] Allow projects tab only to admins with edit or manage roles.
  - [ ] Edit admins can create projects and delete their own projects.
  - [ ] Project edition form: Available for editors and moderators. Admins with only moderate role have disabled all edition fields except change moderation status. When they save the project only moderation status (and maybe publication) is updated.
- [ ] Remove data tab of plans (#2210)
- [ ] When a plan is imported from CSV their projects must be created as published.(#2211)
- [ ] If a moderator updates status of a project from approved to other status, ask if he wants to update publish status to unpublished.(#2208)
- [ ] Add filters to projects tab: Moderation status, edition (my projects, projects I can edit...) and author.(#2212)
- [ ] Display in Plan tab the plan vocabulary decorated with accumulated status and projects (#2213 )
