### ISSUE TITLE
Plans / Plugin: Budgets

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2345]
This plugin, using https://github.com/PopulateTools/gobierto/issues/2343 will provide away to associate budget lines with projects from Planification. An admin must: 

- be able to associate a year and a budget line of that year, assigning a weight for that budget line (in percentage)
- be able to remove associations
- the front-end app should check that Budgets Module is activated and has data, or fail silently otherwise 

Related with this task, we may need to create some API points so an external system can: 

- check available years and budget lines
- get the value of budget and execution for year+budget line combination

**Comment by amiedes** [comment]
@furilo @ferblape 

From which area should the budget lines displayed to the user be from? (economic, functional, custom..)

Does it make sense to make it flexible? (for example by letting the user choose the area when editing the custom field and assigning the plugin)

**Comment by ferblape** [comment]
We need only expenses budget lines. And yes let's make it generic, you could add a select with those options (custom only when there are custom budge lines) together with the year selector.

**Comment by amiedes** [comment]
**Tasks**

- [x] API: Available years
- [x] API: Detailed information about budget line
- [x] API: Available budget lines (for the moment, reuse `/categories`
- [x] Create plugin
- [x] Fix add/updating rows
- [x] Read amout from the selected budget line and display its final amount in a cell depending on the weight
- [x] Take into account when budget amount is not available
- [x] Set amount to "Not available" if request fails
- [ ] ~Dispaly weight as percentage~
- [ ] Avoid http auth for api requests in staging
- [x] Fix markup for plugin type checkbox

**Next iterations**

- [ ] Modify the select2 editor so each row has its own set of available budget lines, depending on the selected year and the selected budget line area
- [ ] Display available budget lines in a more readable way (hierarchy) - Do as with vocabulary terms.

**Comment by amiedes** [comment]
I've deployed this to staging. http://talavan.gobify.net/admin/plans/17/projects/8690/edit

**Comment by amiedes** [comment]
Commenting with @entantoencuanto this and the progress plugin issues we've had doubts about the meaning of the weight column:

![Captura de pantalla 2019-06-24 a las 16 52 10](https://user-images.githubusercontent.com/9287468/60028971-8d3c8c00-96a0-11e9-811a-562ff6016f74.png)

As it is now, it represents the percentage of the budget line assigned to this project.

The other option is that the weight is the percentage of the project money that comes from that budget line (in this case all the percentages should sum up to 100% - and the *assigned amount* column should be removed since it wouldn't make sense).

@ferblape @furilo can you confirm if it right now or it needs to be changed?

**Comment by furilo** [comment]
It's OK as it is.
