### ISSUE TITLE
Investments Module / Meta data of custom fields on

### ISSUE THREAD

**Issue by entantoencuanto** [PopulateTools/gobierto#2541]
- [ ] Add an access point to return information about custom fields, type configuration and useful data for ETL. For example, if a custom field has a vocabulary the list of terms.
- [ ] Allow requests to vocabulary API using the same authentication token as projects investments. This can be used to build custom fields of type table with a column associated with a vocabulary
- [ ] Add meta information in index action response with information about vaules and accumulated. The returned data can be different depending on the type of custom field:
    - For a date field the maximum and minimum value
    - For numeric data the maximum, minimum value and a histogram of values. For this first approach use a default number of intervals for the histogram.
    - For vocabularies the number of elements on each term
