### ISSUE TITLE
Sprint 24/7 - 4/8

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#821]
# Ready

- [ ] #815 Implement Group events and event pages
- [ ] #816 Implement Group news list / news page 
- [ ] #756 Gobierto Attachments inside a module

# In progress

- [ ] #814 Implement Process / Group public view (first iteration) (@amiedes)
- [ ] #755 Gobierto Attachments global section (@apradillap)
- [ ] #753 Global agendas (@ferblape)

# Acceptance

- [ ] #804 Process Group Admin implementation (@amiedes)

# Done
