### ISSUE TITLE
Markup for budget elaboration

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#962]
URL: /presupuestos/elaboracion

### Sections:

- [x] Welcome block
- [x] Comparation vizz including 2018
- [x] Data section
  - [x] General indicators
  - [x] General indicators diff
  - [x] Treemap economic category
  - [x] Treemap functional category
  - [x] Treemap custom category
  - [x] List of budget lines (economic)
  - [x] List of budget lines (functional)
  - [x] List of budget lines (custom)
  - [x] Income / Expense switch
- [x] Evolution graph - maybe this one is problematic to implement
- [x] Budget line explorer

### TODOs:

- [x] Parameterize last year to be shown in bubbles
- [x] New treemap URLs
  - [x] Income
     - [x] Treemap economic category
     - [x] Treemap custom category
  - [x] Expenses
     - [x] Treemap economic category
     - [x] Treemap custom category
     - [x] Treemap functional category

- [x] define how to activate this section (maybe settings in the module?)
- [ ] define global indicators
  - [ ] Global indicators differences
- [x] Table row differences
